AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Fastly::Services::Backend resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/Fastly-Services-Backend/src/handlers.testEntrypoint
      Runtime: nodejs14.x
      CodeUri: ./

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/Fastly-Services-Backend/src/handlers.entrypoint
      Runtime: nodejs14.x
      CodeUri: ./

