---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  The following CloudFormation Fastly resource types allow the creation and configuration of 
  service level objectives, locations, monitors and metrics related to your application.
  This allows kicking off monitoring of new projects simply, efficiently, and consistently.

Parameters:
  DeliveryServiceName:
    Type: String
    Description: Name of the delivery service in Fastly

Mappings:
  CountryMap:
    UK:
      Domain: acme.co.uk
      BackendName: acme.co.uk
      HealthcheckName: "Heathcheck for the UK"
    China:
      Domain: acme.cn
      BackendName: acme.cn
      HealthcheckName: "Heathcheck for China (Mainland)"

Resources:
  # 1. Delivery service
  DeliveryService:
    Type: Fastly::Services::Service
    Properties:
      Name: !Ref DeliveryServiceName

  # 2. Domains
  UKDomain:
    Type: Fastly::Services::Domain
    Properties:
      Name: !FindInMap [CountryMap, UK, Domain]
      Comment: This is a specific domain to access the ACME public webpage in the UK
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId
  ChinaDomain:
    Type: Fastly::Services::Domain
    Properties:
      Name: !FindInMap [CountryMap, China, Domain]
      Comment: This is a specific domain to access the ACME public webpage in China
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId

  # 3. Health checks
  UKHealthcheck:
    Type: Fastly::Services::Healthcheck
    Properties:
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId
      Name: !FindInMap [CountryMap, UK, HealthcheckName]
      CheckInterval: 60000
      Host: !FindInMap [CountryMap, UK, Domain]
      Initial: 1
      Path: "/"
      Threshold: 1
      Timeout: 5000
      Window: 2
  ChinaHealthcheck:
    Type: Fastly::Services::Healthcheck
    Properties:
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId
      Name: !FindInMap [CountryMap, China, HealthcheckName]
      CheckInterval: 60000
      Host: !FindInMap [CountryMap, China, Domain]
      Initial: 1
      Path: "/"
      Threshold: 1
      Timeout: 5000
      Window: 2
  
  # 4. Backends
  UKBackend:
    Type: Fastly::Services::Backend
    DependsOn: UKHealthcheck
    Properties:
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId
      Name: !FindInMap [CountryMap, UK, BackendName]
      Address: !FindInMap [CountryMap, UK, Domain]
      Port: 443
      UseSsl: true
      MinTlsVersion: "1.2"
      Healthcheck: !FindInMap [CountryMap, UK, HealthcheckName]
  ChinaBackend:
    Type: Fastly::Services::Backend
    DependsOn: ChinaHealthcheck
    Properties:
      ServiceId: !GetAtt DeliveryService.Id
      VersionId: !GetAtt DeliveryService.LatestVersionId
      Name: !FindInMap [CountryMap, China, BackendName]
      Address: !FindInMap [CountryMap, China, Domain]
      Port: 443
      UseSsl: true
      MinTlsVersion: "1.2"
      Healthcheck: !FindInMap [CountryMap, China, HealthcheckName]